#pragma once
// Minimal, dependency-free XML reader for the small, well-formed subset of
// OOXML we need to read out of word/document.xml (elements, attributes,
// text nodes, self-closing tags, the 5 predefined XML entities). Not a
// general-purpose XML parser: no DTD, no CDATA, no namespaces beyond
// treating "w:p" etc. as opaque tag names, no comments handling beyond
// skipping them. That's enough for real .docx files, which are always
// generated by well-behaved tools (Word, LibreOffice, ...).
#include <string>
#include <vector>

namespace xmllite {

struct Node {
    std::string tag;                 // e.g. "w:p", empty for a pure text node
    std::string text;                // only set for text nodes (tag empty)
    std::vector<std::pair<std::string, std::string>> attrs;
    std::vector<Node> children;

    bool isText() const { return tag.empty(); }

    const std::string* attr(const std::string& name) const {
        for (const auto& a : attrs) if (a.first == name) return &a.second;
        return nullptr;
    }

    // Concatenates all descendant text node contents, depth-first.
    std::string allText() const {
        std::string out;
        collectText(out);
        return out;
    }

private:
    void collectText(std::string& out) const {
        if (isText()) { out += text; return; }
        for (const auto& c : children) c.collectText(out);
    }
};

std::string unescape(const std::string& in);

// Parses `xml` and returns the list of top-level nodes (normally just one
// root element). Throws std::runtime_error on malformed input.
std::vector<Node> parse(const std::string& xml);

// Depth-first search for all descendant elements with the given tag name
// (root included), in document order.
void findAll(const Node& root, const std::string& tag, std::vector<const Node*>& out);

} // namespace xmllite
